### ISSUE TITLE
Enable API messages are sent solely using TLS version 1.2

### ISSUE THREAD

**Issue by RiteshTC** [topcoder-platform/tc-website#17]
Disable older TLS versions 1.0 & 1.1.
Enable only TLS version 1.2 on the server.
This is required for Payment Gateway

cc @skyhit

**Comment by skyhit** [comment]
@RiteshTC is there a way to verify it?

**Comment by ajefts** [comment]
@skyhit and I tested this in dev and it appears that we are already set to support 1.2 in both dev and prod.  I did a test payment against the Payoneer sanbox to verify.
